version: '3.5'

services:
  postgres: 
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: mahmud
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ny_taxi
    volumes:
       - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw           #adding read and write access to the volume
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "ny_taxi", "-U", "mahmud" ]
      timeout: 45s
      interval: 10s
      retries: 10

    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: "mahmud@admin.com" 
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./pgadmin:/var/lib/pgadmin
    ports:
      - 8080:80